### ISSUE TITLE
Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by wufeiafei** [BANKEX/web3swift#57] opened 2018-04-16 09:11 UTC
hi, I use the method with parameters, and the parameters has more than two objects, but the programe has error,
the code is : 
![1523865852786](https://user-images.githubusercontent.com/3910941/38800219-45f84efe-4199-11e8-93e0-156e4cb1b6f3.jpg)

the intermediate  is nil. and  show: Fatal error: Unexpectedly found nil while unwrapping an Optional value.
=====
what is error?

**Comment by shamatar** [comment] 2018-04-16 09:15
Hello @wufeiafei

Can you post your ABI here, so I can reproduce an issue?

Sincerely, Alex

**Comment by shamatar** [comment] 2018-04-16 09:30
Than your parameter assignment is invalid due to types mismatch. Parameter “r” is bytes32 type and you should pass a value of type «Data” with a length less than or equal to 32 bytes

**Comment by wufeiafei** [comment] 2018-04-16 09:38
hi, when I use this code for the pamameters, the error is also.
![1523871374782](https://user-images.githubusercontent.com/3910941/38801618-e584f910-419c-11e8-9b22-17f0b9471e55.jpg)

**Comment by shamatar** [comment] 2018-04-16 20:02
You should pass "Data" type to parameters, but not [UInt8] that you get from signature[...].bytes method. Although I've added an options to pass an Array<UInt8> instead of data now, it's a not an intended use.

In short, just set
```
let rData = Data(signature[0..<32])
```

and the same way for sData. vData should be converted to BigUInt with 
```
let vData = BigUInt(signature[64])
```

Native types for ABI encoding to work with (so, you can construct an intermediate and don't get nil) are String, Data, EthereumAddress, BigUInt and BigInt, as well as arrays of them.

Sincerely, Alex

**Comment by wufeiafei** [comment] 2018-04-17 07:56
I find a question.
when I use the method "let signature = try Web3Signer.signPersonalMessage(personalMessage!, keystore: keystoreManager!, account: account, password: "BANKEXFOUNDATION")",
the personalMessage  is same, the account is same, password is same, but signature is different every time.

**Comment by skywinder** [comment] 2018-04-18 00:55
Is this issue fixed by #59, @shamatar ?

**Comment by shamatar** [comment] 2018-04-18 08:45
If you add extra parameter “signPersonalMessage(..., useExtraEntropy: false)” your signature will be deterministic

________________________________

**Comment by wufeiafei** [comment] 2018-04-18 08:48
ok, thank you!

**Comment by shamatar** [comment] 2018-04-18 10:34
Closing. ECRecover possible mismatch is discussed in #63

**Closed by shamatar** 2018-04-18 10:34 UTC
