### ISSUE TITLE
Using sendRawTransaction(): error processingError("Transaction is invalid")

### ISSUE THREAD

**Issue by Mateo1999** [BANKEX/web3swift#171] opened 2018-06-30 12:07 UTC
hi @bankexgit  I want to use sendRawTransaction for making transaction But I get the transaction is invalid 
error I don't know what is problem with my code.
thanks

```
    func sendTransaction(From:walletObject, ToWalletAddress:String, value:BigUInt , gasPrice:BigUInt , gasLimit:BigUInt ,
                         owner:UIViewController,
                         success: @escaping (([String:Any]) -> Void),
                         failure: @escaping (([String:Any]) -> Void)){
        let web3 = Web3.new(URL(string: "customURl")!)
        let sendToAddress = EthereumAddress(ToWalletAddress)
        
        var options = Web3Options.defaultOptions()
        options.from = From.EthereumAddress //keystoreManager.addresses?.first
        options.to = sendToAddress
        options.value = value
        options.gasLimit = BigUInt("0")
        options.gasPrice = gasPrice
        
        let transaction = EthereumTransaction(to: EthereumAddress(ToWalletAddress)!, data: "0x".data(using: .utf8)!, options: options)
        let gasLimit = self.getGasLimit(transaction: transaction, option: options)
        print("gasLimit is \(gasLimit)")
        
        options.gasLimit = gasLimit
      
        guard let result = web3?.eth.sendRawTransaction(transaction) else {print("Error for send transaction"); return}
        switch result {
        case .success(let txHash):
            
            DispatchQueue.main.async {
                print("success")
                var result = [String:Any]()
                result["status"] = 200
                result["message"] = "Transfer_Done".localized()
                result["hash"] = txHash.hash
                UtilsFunctions.HideHUD(hud)
                success(result)
            }
            return
        case .failure(let error):
            
            DispatchQueue.main.async {
                print("error \(error)")
                var result = [String:Any]()
                result["error"] = error
                result["status"] = 500
                result["message"] = "Transfer_Failed".localized()
                UtilsFunctions.HideHUD(hud)
                failure(result)
            }
            
        }
}
```

**Comment by shamatar** [comment] 2018-06-30 13:41
Hello @Mateo1999 

First of all, to apply your ```option``` to the transaction, you should use a non-mutating method on transaction called ```mergedWithOptions()``` after this part 
```
        let gasLimit = self.getGasLimit(transaction: transaction, option: options)
        print("gasLimit is \(gasLimit)")
        
        options.gasLimit = gasLimit
```
You did set a gas limit to options, but did not apply it to the transaction. Or you can use ```var``` for transaction and set ```transaction.gasLimit = ....```.

Then you have to sign a transaction using one of the signer classes (```EIP155Signer``` or ```FallbackSigner```). I don't see any signature part in your code at the moment.

Sincerely, Alex

**Comment by shamatar** [comment] 2018-07-02 07:11
Hello @Mateo1999 

This is very strange, couldn't reproduce such bug. All required methods and structures are public and not deprecated.

Also I see you try to assign a result to some variable, although method
```
try Web3Signer.EIP155Signer.sign(transaction: &transaction, privateKey: privateKeyData, useExtraEntropy: false)
```

does NOT return anything, it mutates a passed copy of the transaction itself. So your code should be something like
```
var finalTransaction = transaction.mergedWithOptions(options)
try Web3Signer.EIP155Signer.sign(transaction: &finalTransaction, privateKey: privateKeyData, useExtraEntropy: false)
```

Sincerely, Alex

**Comment by Mateo1999** [comment] 2018-07-02 08:44
Hi @shamatar 
thanks for developing such a great library but I will receive this error.

> execute create user failed: The operation couldn’t be completed. (web3swift.AbstractKeystoreError error 4.)

![photo_2018-07-02_13-11-46](https://user-images.githubusercontent.com/40632293/42153919-b2c0858c-7df9-11e8-9110-7d471ad72a62.jpg)

**Comment by shamatar** [comment] 2018-07-02 15:52
If you use EIP155Signer and your transaction ```chainID``` is nil, than it will fail. Try FallbackSigner first

**Comment by Mateo1999** [comment] 2018-07-03 08:44
Hi @shamatar thank for reply it fixed my problem.

this is code for others:

![photo_2018-07-03_13-12-57](https://user-images.githubusercontent.com/40632293/42209059-f4a6ab9c-7ec2-11e8-8974-f81f7df52f92.jpg)

**Comment by shamatar** [comment] 2018-07-03 13:22
Ok, closing, feel free to reopen if necessary

**Closed by shamatar** 2018-07-03 13:22 UTC
